// Command gendocs generates browseable MkDocs example pages from testdata/cases.
//
//	go run ./hack/gendocs
//
// Output lands under docs/examples/ (committed; regenerated by `make example-docs`).
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"sigs.k8s.io/yaml"
)

const (
	banner     = "<!-- Code generated by `make example-docs` (hack/gendocs). DO NOT EDIT. -->\n\n"
	casesRoot = "testdata/cases"
	defaultOut = "docs/examples"
	repoPrefix = "testdata/cases"
)

type caseManifest struct {
	Description string `json:"description" yaml:"description"`
	Direction   string `json:"direction" yaml:"direction"`
	Issue       string `json:"issue,omitempty" yaml:"issue,omitempty"`
	Name        string `json:"name,omitempty" yaml:"name,omitempty"`
	Namespace   string `json:"namespace,omitempty" yaml:"namespace,omitempty"`
}

type caseInfo struct {
	Subsystem   string
	Name        string
	RelPath     string // subsystem/name
	CaseDir     string
	Manifest    caseManifest
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "gendocs: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := repoRoot()
	if err != nil {
		return err
	}
	outRel := defaultOut
	if v := strings.TrimSpace(os.Getenv("GENDOCS_OUT")); v != "" {
		outRel = v
	}
	casesDir := filepath.Join(root, casesRoot)
	outDir := outRel
	if !filepath.IsAbs(outDir) {
		outDir = filepath.Join(root, outRel)
	}

	cases, err := discoverCases(casesDir)
	if err != nil {
		return err
	}
	if len(cases) == 0 {
		return fmt.Errorf("no cases found under %s", casesDir)
	}

	if err := os.RemoveAll(outDir); err != nil {
		return fmt.Errorf("clear %s: %w", outDir, err)
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}

	bySubsystem := map[string][]caseInfo{}
	for _, c := range cases {
		bySubsystem[c.Subsystem] = append(bySubsystem[c.Subsystem], c)
	}
	subsystems := make([]string, 0, len(bySubsystem))
	for s := range bySubsystem {
		subsystems = append(subsystems, s)
	}
	sort.Strings(subsystems)

	for _, sub := range subsystems {
		list := bySubsystem[sub]
		sort.Slice(list, func(i, j int) bool { return list[i].Name < list[j].Name })
		bySubsystem[sub] = list

		subDir := filepath.Join(outDir, sub)
		if err := os.MkdirAll(subDir, 0o755); err != nil {
			return err
		}
		for _, c := range list {
			page, err := renderCasePage(c)
			if err != nil {
				return fmt.Errorf("%s: %w", c.RelPath, err)
			}
			path := filepath.Join(subDir, c.Name+".md")
			if err := os.WriteFile(path, []byte(page), 0o644); err != nil {
				return err
			}
		}
		idx := renderSubsystemIndex(sub, list)
		if err := os.WriteFile(filepath.Join(subDir, "index.md"), []byte(idx), 0o644); err != nil {
			return err
		}
	}

	if err := os.WriteFile(filepath.Join(outDir, "index.md"), []byte(renderRootIndex(subsystems, bySubsystem)), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(outDir, "SUMMARY.md"), []byte(renderSUMMARY(subsystems, bySubsystem)), 0o644); err != nil {
		return err
	}

	fmt.Printf("gendocs: wrote %d example pages under %s\n", len(cases), outRel)
	return nil
}

func repoRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	dir := wd
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found from %s", wd)
		}
		dir = parent
	}
}

func discoverCases(casesDir string) ([]caseInfo, error) {
	var out []caseInfo
	err := filepath.WalkDir(casesDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || d.Name() != "case.yaml" {
			return nil
		}
		caseDir := filepath.Dir(path)
		rel, err := filepath.Rel(casesDir, caseDir)
		if err != nil {
			return err
		}
		parts := strings.Split(filepath.ToSlash(rel), "/")
		if len(parts) != 2 {
			return fmt.Errorf("unexpected case path depth %q (want subsystem/case)", rel)
		}
		raw, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		var m caseManifest
		if err := yaml.Unmarshal(raw, &m); err != nil {
			return fmt.Errorf("%s: %w", path, err)
		}
		if strings.TrimSpace(m.Description) == "" {
			return fmt.Errorf("%s: description is required", path)
		}
		if strings.TrimSpace(m.Direction) == "" {
			return fmt.Errorf("%s: direction is required", path)
		}
		out = append(out, caseInfo{
			Subsystem: parts[0],
			Name:      parts[1],
			RelPath:   filepath.ToSlash(rel),
			CaseDir:   caseDir,
			Manifest:  m,
		})
		return nil
	})
	sort.Slice(out, func(i, j int) bool { return out[i].RelPath < out[j].RelPath })
	return out, err
}

func renderCasePage(c caseInfo) (string, error) {
	var b strings.Builder
	b.WriteString(banner)
	// Breadcrumbs for CRD users browsing the docs (Material navigation.path is Insiders-only).
	fmt.Fprintf(&b, "[Examples](../index.md) › [%s](index.md) › %s\n\n", c.Subsystem, c.Name)
	fmt.Fprintf(&b, "# %s\n\n", c.Name)
	b.WriteString(c.Manifest.Description)
	b.WriteString("\n\n")
	fmt.Fprintf(&b, "!!! tip \"Direction: `%s`\"\n\n", c.Manifest.Direction)
	b.WriteString("| | |\n| --- | --- |\n")
	fmt.Fprintf(&b, "| Direction | `%s` |\n", c.Manifest.Direction)
	fmt.Fprintf(&b, "| Path | `%s/%s` |\n", repoPrefix, c.RelPath)
	if c.Manifest.Issue != "" {
		fmt.Fprintf(&b, "| Issue | %s |\n", c.Manifest.Issue)
	}
	if c.Manifest.Name != "" {
		fmt.Fprintf(&b, "| CR name | `%s` |\n", c.Manifest.Name)
	}
	if c.Manifest.Namespace != "" {
		fmt.Fprintf(&b, "| Namespace | `%s` |\n", c.Manifest.Namespace)
	}
	b.WriteString("\n")

	inputFiles := []struct {
		name string
		path string
	}{
		{"argocd-cm.yaml", filepath.Join(c.CaseDir, "input", "argocd-cm.yaml")},
		{"argocd-cmd-params-cm.yaml", filepath.Join(c.CaseDir, "input", "argocd-cmd-params-cm.yaml")},
		{"argocd-rbac-cm.yaml", filepath.Join(c.CaseDir, "input", "argocd-rbac-cm.yaml")},
		{"configuration.yaml", filepath.Join(c.CaseDir, "input", "configuration.yaml")},
	}
	var inputBlocks []string
	for _, f := range inputFiles {
		block, err := fenceFile(f.name, f.path)
		if err != nil {
			return "", err
		}
		if block != "" {
			inputBlocks = append(inputBlocks, block)
		}
	}
	if len(inputBlocks) > 0 {
		b.WriteString("## Input\n\n")
		b.WriteString(strings.Join(inputBlocks, "\n"))
		b.WriteString("\n")
	}

	cfgPath := filepath.Join(c.CaseDir, "expected", "configuration.yaml")
	if block, err := fenceFile("configuration.yaml", cfgPath); err != nil {
		return "", err
	} else if block != "" {
		b.WriteString("## Expected ArgoCDConfiguration\n\n")
		b.WriteString(block)
		b.WriteString("\n")
	}

	cmDir := filepath.Join(c.CaseDir, "expected", "configmaps")
	cmNames := []string{"argocd-cm.yaml", "argocd-cmd-params-cm.yaml", "argocd-rbac-cm.yaml"}
	var cmBlocks []string
	for _, name := range cmNames {
		block, err := fenceFile(name, filepath.Join(cmDir, name))
		if err != nil {
			return "", err
		}
		if block != "" {
			cmBlocks = append(cmBlocks, block)
		}
	}
	if len(cmBlocks) > 0 {
		b.WriteString("## Expected ConfigMaps\n\n")
		b.WriteString(strings.Join(cmBlocks, "\n"))
		b.WriteString("\n")
	}

	diagPath := filepath.Join(c.CaseDir, "expected", "diagnostics.yaml")
	if block, err := fenceFile("diagnostics.yaml", diagPath); err != nil {
		return "", err
	} else if block != "" && !isEffectivelyEmptyYAML(diagPath) {
		b.WriteString("## Diagnostics\n\n")
		b.WriteString(block)
		b.WriteString("\n")
	}

	return b.String(), nil
}

func fenceFile(title, path string) (string, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	// Follow symlinks' content (already via ReadFile).
	content := string(raw)
	if !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	var b strings.Builder
	fmt.Fprintf(&b, "### `%s`\n\n", title)
	b.WriteString("```yaml\n")
	b.WriteString(content)
	b.WriteString("```\n")
	return b.String(), nil
}

func isEffectivelyEmptyYAML(path string) bool {
	raw, err := os.ReadFile(path)
	if err != nil {
		return true
	}
	s := strings.TrimSpace(string(raw))
	return s == "" || s == "{}" || s == "[]" || s == "null"
}

func renderSubsystemIndex(sub string, cases []caseInfo) string {
	var b strings.Builder
	b.WriteString(banner)
	fmt.Fprintf(&b, "[Examples](../index.md) › %s\n\n", sub)
	fmt.Fprintf(&b, "# %s\n\n", sub)
	b.WriteString("Golden conversion cases under this subsystem.\n\n")
	b.WriteString("| Case | Direction | Description |\n")
	b.WriteString("| --- | --- | --- |\n")
	for _, c := range cases {
		fmt.Fprintf(&b, "| [%s](%s.md) | `%s` | %s |\n", c.Name, c.Name, c.Manifest.Direction, escapeTableCell(c.Manifest.Description))
	}
	b.WriteString("\n")
	return b.String()
}

func renderRootIndex(subsystems []string, bySubsystem map[string][]caseInfo) string {
	var b strings.Builder
	b.WriteString(banner)
	b.WriteString("# Examples\n\n")
	b.WriteString("These pages are generated from the golden test corpus under `testdata/cases/`.\n")
	b.WriteString("Each example shows the case inputs and expected conversion outputs.\n\n")
	b.WriteString("| Subsystem | Cases |\n")
	b.WriteString("| --- | --- |\n")
	for _, sub := range subsystems {
		cases := bySubsystem[sub]
		links := make([]string, 0, len(cases))
		for _, c := range cases {
			links = append(links, fmt.Sprintf("[%s](%s/%s.md)", c.Name, sub, c.Name))
		}
		fmt.Fprintf(&b, "| [%s](%s/index.md) | %s |\n", sub, sub, strings.Join(links, ", "))
	}
	b.WriteString("\n")
	return b.String()
}

func renderSUMMARY(subsystems []string, bySubsystem map[string][]caseInfo) string {
	// Literate-nav format: markdown list of links relative to docs/examples/
	var b strings.Builder
	b.WriteString(banner)
	b.WriteString("* [Overview](index.md)\n")
	for _, sub := range subsystems {
		fmt.Fprintf(&b, "* [%s](%s/index.md)\n", sub, sub)
		for _, c := range bySubsystem[sub] {
			fmt.Fprintf(&b, "    * [%s](%s/%s.md)\n", c.Name, sub, c.Name)
		}
	}
	return b.String()
}

func escapeTableCell(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}
