//go:build !ignore_autogenerated

/*
Copyright 2026 Michael Crenshaw / crenshaw-dev.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountConfig) DeepCopyInto(out *AccountConfig) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountConfig.
func (in *AccountConfig) DeepCopy() *AccountConfig {
	if in == nil {
		return nil
	}
	out := new(AccountConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationSetConfig) DeepCopyInto(out *ApplicationSetConfig) {
	*out = *in
	if in.NamespaceGlobs != nil {
		in, out := &in.NamespaceGlobs, &out.NamespaceGlobs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedSCMProviderURLs != nil {
		in, out := &in.AllowedSCMProviderURLs, &out.AllowedSCMProviderURLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GlobalPreserved != nil {
		in, out := &in.GlobalPreserved, &out.GlobalPreserved
		*out = new(GlobalPreservedKeysConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SCMProvidersEnabled != nil {
		in, out := &in.SCMProvidersEnabled, &out.SCMProvidersEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PolicyOverrideEnabled != nil {
		in, out := &in.PolicyOverrideEnabled, &out.PolicyOverrideEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ProgressiveSyncs != nil {
		in, out := &in.ProgressiveSyncs, &out.ProgressiveSyncs
		*out = new(ProgressiveSyncsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.GitSubmoduleEnabled != nil {
		in, out := &in.GitSubmoduleEnabled, &out.GitSubmoduleEnabled
		*out = new(bool)
		**out = **in
	}
	if in.NewGitFileGlobbingEnabled != nil {
		in, out := &in.NewGitFileGlobbingEnabled, &out.NewGitFileGlobbingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TokenRefStrictModeEnabled != nil {
		in, out := &in.TokenRefStrictModeEnabled, &out.TokenRefStrictModeEnabled
		*out = new(bool)
		**out = **in
	}
	if in.GitHubAPIMetricsEnabled != nil {
		in, out := &in.GitHubAPIMetricsEnabled, &out.GitHubAPIMetricsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DryRun != nil {
		in, out := &in.DryRun, &out.DryRun
		*out = new(bool)
		**out = **in
	}
	if in.LeaderElectionEnabled != nil {
		in, out := &in.LeaderElectionEnabled, &out.LeaderElectionEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ReconciliationsParallelismLimit != nil {
		in, out := &in.ReconciliationsParallelismLimit, &out.ReconciliationsParallelismLimit
		*out = new(int32)
		**out = **in
	}
	if in.RequeueAfter != nil {
		in, out := &in.RequeueAfter, &out.RequeueAfter
		*out = new(v1.Duration)
		**out = **in
	}
	if in.WebhookParallelismLimit != nil {
		in, out := &in.WebhookParallelismLimit, &out.WebhookParallelismLimit
		*out = new(int32)
		**out = **in
	}
	if in.StatusMaxResourcesCount != nil {
		in, out := &in.StatusMaxResourcesCount, &out.StatusMaxResourcesCount
		*out = new(int32)
		**out = **in
	}
	if in.Log != nil {
		in, out := &in.Log, &out.Log
		*out = new(LogConfig)
		**out = **in
	}
	if in.ProfileEnabled != nil {
		in, out := &in.ProfileEnabled, &out.ProfileEnabled
		*out = new(bool)
		**out = **in
	}
	if in.GRPCTXTServiceConfigEnabled != nil {
		in, out := &in.GRPCTXTServiceConfigEnabled, &out.GRPCTXTServiceConfigEnabled
		*out = new(bool)
		**out = **in
	}
	if in.K8sClient != nil {
		in, out := &in.K8sClient, &out.K8sClient
		*out = new(K8sClientConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RepoServerClient != nil {
		in, out := &in.RepoServerClient, &out.RepoServerClient
		*out = new(MTLSCertConfig)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(ApplicationSetMetricsConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationSetConfig.
func (in *ApplicationSetConfig) DeepCopy() *ApplicationSetConfig {
	if in == nil {
		return nil
	}
	out := new(ApplicationSetConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationSetMetricsConfig) DeepCopyInto(out *ApplicationSetMetricsConfig) {
	*out = *in
	if in.ApplicationSetLabels != nil {
		in, out := &in.ApplicationSetLabels, &out.ApplicationSetLabels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationSetMetricsConfig.
func (in *ApplicationSetMetricsConfig) DeepCopy() *ApplicationSetMetricsConfig {
	if in == nil {
		return nil
	}
	out := new(ApplicationSetMetricsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationSyncConfig) DeepCopyInto(out *ApplicationSyncConfig) {
	*out = *in
	if in.Impersonation != nil {
		in, out := &in.Impersonation, &out.Impersonation
		*out = new(SyncImpersonationConfig)
		**out = **in
	}
	if in.RequireOverridePrivilegeForRevisionSync != nil {
		in, out := &in.RequireOverridePrivilegeForRevisionSync, &out.RequireOverridePrivilegeForRevisionSync
		*out = new(bool)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Wave != nil {
		in, out := &in.Wave, &out.Wave
		*out = new(SyncWaveConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationSyncConfig.
func (in *ApplicationSyncConfig) DeepCopy() *ApplicationSyncConfig {
	if in == nil {
		return nil
	}
	out := new(ApplicationSyncConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDConfiguration) DeepCopyInto(out *ArgoCDConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDConfiguration.
func (in *ArgoCDConfiguration) DeepCopy() *ArgoCDConfiguration {
	if in == nil {
		return nil
	}
	out := new(ArgoCDConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArgoCDConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDConfigurationList) DeepCopyInto(out *ArgoCDConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArgoCDConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDConfigurationList.
func (in *ArgoCDConfigurationList) DeepCopy() *ArgoCDConfigurationList {
	if in == nil {
		return nil
	}
	out := new(ArgoCDConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArgoCDConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDConfigurationSpec) DeepCopyInto(out *ArgoCDConfigurationSpec) {
	*out = *in
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(ServerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Controller != nil {
		in, out := &in.Controller, &out.Controller
		*out = new(ControllerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RepoServer != nil {
		in, out := &in.RepoServer, &out.RepoServer
		*out = new(RepoServerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CommitServer != nil {
		in, out := &in.CommitServer, &out.CommitServer
		*out = new(CommitServerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplicationSet != nil {
		in, out := &in.ApplicationSet, &out.ApplicationSet
		*out = new(ApplicationSetConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(ClusterConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Redis != nil {
		in, out := &in.Redis, &out.Redis
		*out = new(RedisConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.OTLP != nil {
		in, out := &in.OTLP, &out.OTLP
		*out = new(OTLPConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplicationNamespaceGlobs != nil {
		in, out := &in.ApplicationNamespaceGlobs, &out.ApplicationNamespaceGlobs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExecTimeout != nil {
		in, out := &in.ExecTimeout, &out.ExecTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.DexServer != nil {
		in, out := &in.DexServer, &out.DexServer
		*out = new(DexServerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = new(NotificationsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(LoggingConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDConfigurationSpec.
func (in *ArgoCDConfigurationSpec) DeepCopy() *ArgoCDConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureOIDCConfig) DeepCopyInto(out *AzureOIDCConfig) {
	*out = *in
	if in.UserGroupOverageClaim != nil {
		in, out := &in.UserGroupOverageClaim, &out.UserGroupOverageClaim
		*out = new(AzureUserGroupOverageClaimConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureOIDCConfig.
func (in *AzureOIDCConfig) DeepCopy() *AzureOIDCConfig {
	if in == nil {
		return nil
	}
	out := new(AzureOIDCConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureUserGroupOverageClaimConfig) DeepCopyInto(out *AzureUserGroupOverageClaimConfig) {
	*out = *in
	if in.CacheExpiration != nil {
		in, out := &in.CacheExpiration, &out.CacheExpiration
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureUserGroupOverageClaimConfig.
func (in *AzureUserGroupOverageClaimConfig) DeepCopy() *AzureUserGroupOverageClaimConfig {
	if in == nil {
		return nil
	}
	out := new(AzureUserGroupOverageClaimConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackoffConfig) DeepCopyInto(out *BackoffConfig) {
	*out = *in
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Factor != nil {
		in, out := &in.Factor, &out.Factor
		*out = new(int32)
		**out = **in
	}
	if in.MaxDuration != nil {
		in, out := &in.MaxDuration, &out.MaxDuration
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackoffConfig.
func (in *BackoffConfig) DeepCopy() *BackoffConfig {
	if in == nil {
		return nil
	}
	out := new(BackoffConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientRetryConfig) DeepCopyInto(out *ClientRetryConfig) {
	*out = *in
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		*out = new(int32)
		**out = **in
	}
	if in.Backoff != nil {
		in, out := &in.Backoff, &out.Backoff
		*out = new(BackoffConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientRetryConfig.
func (in *ClientRetryConfig) DeepCopy() *ClientRetryConfig {
	if in == nil {
		return nil
	}
	out := new(ClientRetryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConfig) DeepCopyInto(out *ClusterConfig) {
	*out = *in
	if in.InClusterEnabled != nil {
		in, out := &in.InClusterEnabled, &out.InClusterEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConfig.
func (in *ClusterConfig) DeepCopy() *ClusterConfig {
	if in == nil {
		return nil
	}
	out := new(ClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommitAuthor) DeepCopyInto(out *CommitAuthor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommitAuthor.
func (in *CommitAuthor) DeepCopy() *CommitAuthor {
	if in == nil {
		return nil
	}
	out := new(CommitAuthor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommitConfig) DeepCopyInto(out *CommitConfig) {
	*out = *in
	if in.Author != nil {
		in, out := &in.Author, &out.Author
		*out = new(CommitAuthor)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommitConfig.
func (in *CommitConfig) DeepCopy() *CommitConfig {
	if in == nil {
		return nil
	}
	out := new(CommitConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommitServerConfig) DeepCopyInto(out *CommitServerConfig) {
	*out = *in
	if in.Listen != nil {
		in, out := &in.Listen, &out.Listen
		*out = new(ListenConfig)
		**out = **in
	}
	if in.GRPCTXTServiceConfigEnabled != nil {
		in, out := &in.GRPCTXTServiceConfigEnabled, &out.GRPCTXTServiceConfigEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Commit != nil {
		in, out := &in.Commit, &out.Commit
		*out = new(CommitConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Log != nil {
		in, out := &in.Log, &out.Log
		*out = new(LogConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommitServerConfig.
func (in *CommitServerConfig) DeepCopy() *CommitServerConfig {
	if in == nil {
		return nil
	}
	out := new(CommitServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompareOptions) DeepCopyInto(out *CompareOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompareOptions.
func (in *CompareOptions) DeepCopy() *CompareOptions {
	if in == nil {
		return nil
	}
	out := new(CompareOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerCacheConfig) DeepCopyInto(out *ControllerCacheConfig) {
	*out = *in
	if in.AppStateExpiration != nil {
		in, out := &in.AppStateExpiration, &out.AppStateExpiration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.DefaultExpiration != nil {
		in, out := &in.DefaultExpiration, &out.DefaultExpiration
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerCacheConfig.
func (in *ControllerCacheConfig) DeepCopy() *ControllerCacheConfig {
	if in == nil {
		return nil
	}
	out := new(ControllerCacheConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerClusterCacheConfig) DeepCopyInto(out *ControllerClusterCacheConfig) {
	*out = *in
	if in.BatchEventsProcessing != nil {
		in, out := &in.BatchEventsProcessing, &out.BatchEventsProcessing
		*out = new(bool)
		**out = **in
	}
	if in.EventsProcessingInterval != nil {
		in, out := &in.EventsProcessingInterval, &out.EventsProcessingInterval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerClusterCacheConfig.
func (in *ControllerClusterCacheConfig) DeepCopy() *ControllerClusterCacheConfig {
	if in == nil {
		return nil
	}
	out := new(ControllerClusterCacheConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfig) DeepCopyInto(out *ControllerConfig) {
	*out = *in
	if in.Reconciliation != nil {
		in, out := &in.Reconciliation, &out.Reconciliation
		*out = new(ReconciliationConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Sharding != nil {
		in, out := &in.Sharding, &out.Sharding
		*out = new(ControllerShardingConfig)
		**out = **in
	}
	if in.Processors != nil {
		in, out := &in.Processors, &out.Processors
		*out = new(ControllerProcessorsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Log != nil {
		in, out := &in.Log, &out.Log
		*out = new(LogConfig)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(ControllerMetricsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SelfHeal != nil {
		in, out := &in.SelfHeal, &out.SelfHeal
		*out = new(SelfHealConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(ControllerCacheConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceHealthPersist != nil {
		in, out := &in.ResourceHealthPersist, &out.ResourceHealthPersist
		*out = new(bool)
		**out = **in
	}
	if in.KubectlParallelismLimit != nil {
		in, out := &in.KubectlParallelismLimit, &out.KubectlParallelismLimit
		*out = new(int32)
		**out = **in
	}
	if in.Diff != nil {
		in, out := &in.Diff, &out.Diff
		*out = new(ControllerDiffConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ProfileEnabled != nil {
		in, out := &in.ProfileEnabled, &out.ProfileEnabled
		*out = new(bool)
		**out = **in
	}
	if in.GRPCTXTServiceConfigEnabled != nil {
		in, out := &in.GRPCTXTServiceConfigEnabled, &out.GRPCTXTServiceConfigEnabled
		*out = new(bool)
		**out = **in
	}
	if in.RepoErrorGracePeriod != nil {
		in, out := &in.RepoErrorGracePeriod, &out.RepoErrorGracePeriod
		*out = new(v1.Duration)
		**out = **in
	}
	if in.ClusterCache != nil {
		in, out := &in.ClusterCache, &out.ClusterCache
		*out = new(ControllerClusterCacheConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.K8sClient != nil {
		in, out := &in.K8sClient, &out.K8sClient
		*out = new(K8sClientConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(ResourceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowedNodeLabelKeys != nil {
		in, out := &in.AllowedNodeLabelKeys, &out.AllowedNodeLabelKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Sync != nil {
		in, out := &in.Sync, &out.Sync
		*out = new(ApplicationSyncConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.GlobalProjects != nil {
		in, out := &in.GlobalProjects, &out.GlobalProjects
		*out = make([]GlobalProjectConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SourceHydrator != nil {
		in, out := &in.SourceHydrator, &out.SourceHydrator
		*out = new(SourceHydratorConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfig.
func (in *ControllerConfig) DeepCopy() *ControllerConfig {
	if in == nil {
		return nil
	}
	out := new(ControllerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerDiffConfig) DeepCopyInto(out *ControllerDiffConfig) {
	*out = *in
	if in.ServerSide != nil {
		in, out := &in.ServerSide, &out.ServerSide
		*out = new(DiffServerSideConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CompareOptions != nil {
		in, out := &in.CompareOptions, &out.CompareOptions
		*out = new(CompareOptions)
		**out = **in
	}
	if in.IgnoreResourceUpdatesEnabled != nil {
		in, out := &in.IgnoreResourceUpdatesEnabled, &out.IgnoreResourceUpdatesEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IgnoreNormalizerJQTimeout != nil {
		in, out := &in.IgnoreNormalizerJQTimeout, &out.IgnoreNormalizerJQTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerDiffConfig.
func (in *ControllerDiffConfig) DeepCopy() *ControllerDiffConfig {
	if in == nil {
		return nil
	}
	out := new(ControllerDiffConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerMetricsApplicationConfig) DeepCopyInto(out *ControllerMetricsApplicationConfig) {
	*out = *in
	if in.LabelKeys != nil {
		in, out := &in.LabelKeys, &out.LabelKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerMetricsApplicationConfig.
func (in *ControllerMetricsApplicationConfig) DeepCopy() *ControllerMetricsApplicationConfig {
	if in == nil {
		return nil
	}
	out := new(ControllerMetricsApplicationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerMetricsClusterConfig) DeepCopyInto(out *ControllerMetricsClusterConfig) {
	*out = *in
	if in.LabelKeys != nil {
		in, out := &in.LabelKeys, &out.LabelKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerMetricsClusterConfig.
func (in *ControllerMetricsClusterConfig) DeepCopy() *ControllerMetricsClusterConfig {
	if in == nil {
		return nil
	}
	out := new(ControllerMetricsClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerMetricsConfig) DeepCopyInto(out *ControllerMetricsConfig) {
	*out = *in
	if in.CacheExpiration != nil {
		in, out := &in.CacheExpiration, &out.CacheExpiration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Application != nil {
		in, out := &in.Application, &out.Application
		*out = new(ControllerMetricsApplicationConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(ControllerMetricsClusterConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerMetricsConfig.
func (in *ControllerMetricsConfig) DeepCopy() *ControllerMetricsConfig {
	if in == nil {
		return nil
	}
	out := new(ControllerMetricsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerProcessorsConfig) DeepCopyInto(out *ControllerProcessorsConfig) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(int32)
		**out = **in
	}
	if in.Operation != nil {
		in, out := &in.Operation, &out.Operation
		*out = new(int32)
		**out = **in
	}
	if in.Hydration != nil {
		in, out := &in.Hydration, &out.Hydration
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerProcessorsConfig.
func (in *ControllerProcessorsConfig) DeepCopy() *ControllerProcessorsConfig {
	if in == nil {
		return nil
	}
	out := new(ControllerProcessorsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerShardingConfig) DeepCopyInto(out *ControllerShardingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerShardingConfig.
func (in *ControllerShardingConfig) DeepCopy() *ControllerShardingConfig {
	if in == nil {
		return nil
	}
	out := new(ControllerShardingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeepLink) DeepCopyInto(out *DeepLink) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeepLink.
func (in *DeepLink) DeepCopy() *DeepLink {
	if in == nil {
		return nil
	}
	out := new(DeepLink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeepLinksConfig) DeepCopyInto(out *DeepLinksConfig) {
	*out = *in
	if in.Application != nil {
		in, out := &in.Application, &out.Application
		*out = make([]DeepLink, len(*in))
		copy(*out, *in)
	}
	if in.Project != nil {
		in, out := &in.Project, &out.Project
		*out = make([]DeepLink, len(*in))
		copy(*out, *in)
	}
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = make([]DeepLink, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeepLinksConfig.
func (in *DeepLinksConfig) DeepCopy() *DeepLinksConfig {
	if in == nil {
		return nil
	}
	out := new(DeepLinksConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexConfig) DeepCopyInto(out *DexConfig) {
	*out = *in
	if in.Connectors != nil {
		in, out := &in.Connectors, &out.Connectors
		*out = make([]DexConnector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StaticClients != nil {
		in, out := &in.StaticClients, &out.StaticClients
		*out = make([]runtime.RawExtension, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Extra != nil {
		in, out := &in.Extra, &out.Extra
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexConfig.
func (in *DexConfig) DeepCopy() *DexConfig {
	if in == nil {
		return nil
	}
	out := new(DexConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexConnectionConfig) DeepCopyInto(out *DexConnectionConfig) {
	*out = *in
	if in.TLSEnabled != nil {
		in, out := &in.TLSEnabled, &out.TLSEnabled
		*out = new(bool)
		**out = **in
	}
	if in.InsecureSkipVerify != nil {
		in, out := &in.InsecureSkipVerify, &out.InsecureSkipVerify
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexConnectionConfig.
func (in *DexConnectionConfig) DeepCopy() *DexConnectionConfig {
	if in == nil {
		return nil
	}
	out := new(DexConnectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexConnector) DeepCopyInto(out *DexConnector) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexConnector.
func (in *DexConnector) DeepCopy() *DexConnector {
	if in == nil {
		return nil
	}
	out := new(DexConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DexServerConfig) DeepCopyInto(out *DexServerConfig) {
	*out = *in
	if in.Log != nil {
		in, out := &in.Log, &out.Log
		*out = new(LogConfig)
		**out = **in
	}
	if in.TLSEnabled != nil {
		in, out := &in.TLSEnabled, &out.TLSEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ConnectorFailureContinue != nil {
		in, out := &in.ConnectorFailureContinue, &out.ConnectorFailureContinue
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DexServerConfig.
func (in *DexServerConfig) DeepCopy() *DexServerConfig {
	if in == nil {
		return nil
	}
	out := new(DexServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiffServerSideConfig) DeepCopyInto(out *DiffServerSideConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiffServerSideConfig.
func (in *DiffServerSideConfig) DeepCopy() *DiffServerSideConfig {
	if in == nil {
		return nil
	}
	out := new(DiffServerSideConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventLabelsConfig) DeepCopyInto(out *EventLabelsConfig) {
	*out = *in
	if in.IncludeKeyGlobs != nil {
		in, out := &in.IncludeKeyGlobs, &out.IncludeKeyGlobs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeKeyGlobs != nil {
		in, out := &in.ExcludeKeyGlobs, &out.ExcludeKeyGlobs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventLabelsConfig.
func (in *EventLabelsConfig) DeepCopy() *EventLabelsConfig {
	if in == nil {
		return nil
	}
	out := new(EventLabelsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecConfig) DeepCopyInto(out *ExecConfig) {
	*out = *in
	if in.Shells != nil {
		in, out := &in.Shells, &out.Shells
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecConfig.
func (in *ExecConfig) DeepCopy() *ExecConfig {
	if in == nil {
		return nil
	}
	out := new(ExecConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionBackend) DeepCopyInto(out *ExtensionBackend) {
	*out = *in
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]ExtensionService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Transport != nil {
		in, out := &in.Transport, &out.Transport
		*out = new(ExtensionTransportConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionBackend.
func (in *ExtensionBackend) DeepCopy() *ExtensionBackend {
	if in == nil {
		return nil
	}
	out := new(ExtensionBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionCluster) DeepCopyInto(out *ExtensionCluster) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionCluster.
func (in *ExtensionCluster) DeepCopy() *ExtensionCluster {
	if in == nil {
		return nil
	}
	out := new(ExtensionCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionConfig) DeepCopyInto(out *ExtensionConfig) {
	*out = *in
	in.Backend.DeepCopyInto(&out.Backend)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionConfig.
func (in *ExtensionConfig) DeepCopy() *ExtensionConfig {
	if in == nil {
		return nil
	}
	out := new(ExtensionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionHeader) DeepCopyInto(out *ExtensionHeader) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionHeader.
func (in *ExtensionHeader) DeepCopy() *ExtensionHeader {
	if in == nil {
		return nil
	}
	out := new(ExtensionHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionService) DeepCopyInto(out *ExtensionService) {
	*out = *in
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(ExtensionCluster)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]ExtensionHeader, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionService.
func (in *ExtensionService) DeepCopy() *ExtensionService {
	if in == nil {
		return nil
	}
	out := new(ExtensionService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionTransportConfig) DeepCopyInto(out *ExtensionTransportConfig) {
	*out = *in
	if in.ConnectionTimeout != nil {
		in, out := &in.ConnectionTimeout, &out.ConnectionTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.KeepAlive != nil {
		in, out := &in.KeepAlive, &out.KeepAlive
		*out = new(v1.Duration)
		**out = **in
	}
	if in.IdleConnectionTimeout != nil {
		in, out := &in.IdleConnectionTimeout, &out.IdleConnectionTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionTransportConfig.
func (in *ExtensionTransportConfig) DeepCopy() *ExtensionTransportConfig {
	if in == nil {
		return nil
	}
	out := new(ExtensionTransportConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilteredResource) DeepCopyInto(out *FilteredResource) {
	*out = *in
	if in.APIGroups != nil {
		in, out := &in.APIGroups, &out.APIGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Kinds != nil {
		in, out := &in.Kinds, &out.Kinds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilteredResource.
func (in *FilteredResource) DeepCopy() *FilteredResource {
	if in == nil {
		return nil
	}
	out := new(FilteredResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalPreservedKeysConfig) DeepCopyInto(out *GlobalPreservedKeysConfig) {
	*out = *in
	if in.AnnotationKeys != nil {
		in, out := &in.AnnotationKeys, &out.AnnotationKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LabelKeys != nil {
		in, out := &in.LabelKeys, &out.LabelKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalPreservedKeysConfig.
func (in *GlobalPreservedKeysConfig) DeepCopy() *GlobalPreservedKeysConfig {
	if in == nil {
		return nil
	}
	out := new(GlobalPreservedKeysConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalProjectConfig) DeepCopyInto(out *GlobalProjectConfig) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalProjectConfig.
func (in *GlobalProjectConfig) DeepCopy() *GlobalProjectConfig {
	if in == nil {
		return nil
	}
	out := new(GlobalProjectConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleAnalyticsConfig) DeepCopyInto(out *GoogleAnalyticsConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleAnalyticsConfig.
func (in *GoogleAnalyticsConfig) DeepCopy() *GoogleAnalyticsConfig {
	if in == nil {
		return nil
	}
	out := new(GoogleAnalyticsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmConfig) DeepCopyInto(out *HelmConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ValuesFileSchemes != nil {
		in, out := &in.ValuesFileSchemes, &out.ValuesFileSchemes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Manifest != nil {
		in, out := &in.Manifest, &out.Manifest
		*out = new(HelmManifestConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmConfig.
func (in *HelmConfig) DeepCopy() *HelmConfig {
	if in == nil {
		return nil
	}
	out := new(HelmConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmManifestConfig) DeepCopyInto(out *HelmManifestConfig) {
	*out = *in
	if in.MaxExtractedSize != nil {
		in, out := &in.MaxExtractedSize, &out.MaxExtractedSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxExtractedSizeEnabled != nil {
		in, out := &in.MaxExtractedSizeEnabled, &out.MaxExtractedSizeEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmManifestConfig.
func (in *HelmManifestConfig) DeepCopy() *HelmManifestConfig {
	if in == nil {
		return nil
	}
	out := new(HelmManifestConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelpChatConfig) DeepCopyInto(out *HelpChatConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelpChatConfig.
func (in *HelpChatConfig) DeepCopy() *HelpChatConfig {
	if in == nil {
		return nil
	}
	out := new(HelpChatConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelpConfig) DeepCopyInto(out *HelpConfig) {
	*out = *in
	if in.Chat != nil {
		in, out := &in.Chat, &out.Chat
		*out = new(HelpChatConfig)
		**out = **in
	}
	if in.BinaryURLs != nil {
		in, out := &in.BinaryURLs, &out.BinaryURLs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelpConfig.
func (in *HelpConfig) DeepCopy() *HelpConfig {
	if in == nil {
		return nil
	}
	out := new(HelpConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JsonnetConfig) DeepCopyInto(out *JsonnetConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JsonnetConfig.
func (in *JsonnetConfig) DeepCopy() *JsonnetConfig {
	if in == nil {
		return nil
	}
	out := new(JsonnetConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sClientConfig) DeepCopyInto(out *K8sClientConfig) {
	*out = *in
	if in.Burst != nil {
		in, out := &in.Burst, &out.Burst
		*out = new(int32)
		**out = **in
	}
	if in.MaxIdleConnections != nil {
		in, out := &in.MaxIdleConnections, &out.MaxIdleConnections
		*out = new(int32)
		**out = **in
	}
	if in.TCP != nil {
		in, out := &in.TCP, &out.TCP
		*out = new(K8sClientTCPConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TLSHandshakeTimeout != nil {
		in, out := &in.TLSHandshakeTimeout, &out.TLSHandshakeTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Retry != nil {
		in, out := &in.Retry, &out.Retry
		*out = new(ClientRetryConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sClientConfig.
func (in *K8sClientConfig) DeepCopy() *K8sClientConfig {
	if in == nil {
		return nil
	}
	out := new(K8sClientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sClientTCPConfig) DeepCopyInto(out *K8sClientTCPConfig) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.KeepAlive != nil {
		in, out := &in.KeepAlive, &out.KeepAlive
		*out = new(v1.Duration)
		**out = **in
	}
	if in.IdleTimeout != nil {
		in, out := &in.IdleTimeout, &out.IdleTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sClientTCPConfig.
func (in *K8sClientTCPConfig) DeepCopy() *K8sClientTCPConfig {
	if in == nil {
		return nil
	}
	out := new(K8sClientTCPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnownTypeField) DeepCopyInto(out *KnownTypeField) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnownTypeField.
func (in *KnownTypeField) DeepCopy() *KnownTypeField {
	if in == nil {
		return nil
	}
	out := new(KnownTypeField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KustomizeConfig) DeepCopyInto(out *KustomizeConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Versions != nil {
		in, out := &in.Versions, &out.Versions
		*out = make([]KustomizeVersion, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KustomizeConfig.
func (in *KustomizeConfig) DeepCopy() *KustomizeConfig {
	if in == nil {
		return nil
	}
	out := new(KustomizeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KustomizeVersion) DeepCopyInto(out *KustomizeVersion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KustomizeVersion.
func (in *KustomizeVersion) DeepCopy() *KustomizeVersion {
	if in == nil {
		return nil
	}
	out := new(KustomizeVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenConfig) DeepCopyInto(out *ListenConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenConfig.
func (in *ListenConfig) DeepCopy() *ListenConfig {
	if in == nil {
		return nil
	}
	out := new(ListenConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogConfig) DeepCopyInto(out *LogConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogConfig.
func (in *LogConfig) DeepCopy() *LogConfig {
	if in == nil {
		return nil
	}
	out := new(LogConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingConfig) DeepCopyInto(out *LoggingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingConfig.
func (in *LoggingConfig) DeepCopy() *LoggingConfig {
	if in == nil {
		return nil
	}
	out := new(LoggingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MTLSCertConfig) DeepCopyInto(out *MTLSCertConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MTLSCertConfig.
func (in *MTLSCertConfig) DeepCopy() *MTLSCertConfig {
	if in == nil {
		return nil
	}
	out := new(MTLSCertConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationsConfig) DeepCopyInto(out *NotificationsConfig) {
	*out = *in
	if in.Log != nil {
		in, out := &in.Log, &out.Log
		*out = new(LogConfig)
		**out = **in
	}
	if in.ProcessorsCount != nil {
		in, out := &in.ProcessorsCount, &out.ProcessorsCount
		*out = new(int32)
		**out = **in
	}
	if in.SelfServiceEnabled != nil {
		in, out := &in.SelfServiceEnabled, &out.SelfServiceEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TLSEnabled != nil {
		in, out := &in.TLSEnabled, &out.TLSEnabled
		*out = new(bool)
		**out = **in
	}
	if in.RepoServerClient != nil {
		in, out := &in.RepoServerClient, &out.RepoServerClient
		*out = new(MTLSCertConfig)
		**out = **in
	}
	if in.RepoServerStrictTLS != nil {
		in, out := &in.RepoServerStrictTLS, &out.RepoServerStrictTLS
		*out = new(bool)
		**out = **in
	}
	if in.MetricsPort != nil {
		in, out := &in.MetricsPort, &out.MetricsPort
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationsConfig.
func (in *NotificationsConfig) DeepCopy() *NotificationsConfig {
	if in == nil {
		return nil
	}
	out := new(NotificationsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIManifestConfig) DeepCopyInto(out *OCIManifestConfig) {
	*out = *in
	if in.MaxExtractedSize != nil {
		in, out := &in.MaxExtractedSize, &out.MaxExtractedSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxExtractedSizeEnabled != nil {
		in, out := &in.MaxExtractedSizeEnabled, &out.MaxExtractedSizeEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIManifestConfig.
func (in *OCIManifestConfig) DeepCopy() *OCIManifestConfig {
	if in == nil {
		return nil
	}
	out := new(OCIManifestConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCClaim) DeepCopyInto(out *OIDCClaim) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCClaim.
func (in *OIDCClaim) DeepCopy() *OIDCClaim {
	if in == nil {
		return nil
	}
	out := new(OIDCClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCConfig) DeepCopyInto(out *OIDCConfig) {
	*out = *in
	if in.ClientSecretRef != nil {
		in, out := &in.ClientSecretRef, &out.ClientSecretRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.UserInfo != nil {
		in, out := &in.UserInfo, &out.UserInfo
		*out = new(OIDCUserInfoConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RequestedScopes != nil {
		in, out := &in.RequestedScopes, &out.RequestedScopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequestedIDTokenClaims != nil {
		in, out := &in.RequestedIDTokenClaims, &out.RequestedIDTokenClaims
		*out = make(map[string]OIDCClaim, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(AzureOIDCConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RefreshTokenThreshold != nil {
		in, out := &in.RefreshTokenThreshold, &out.RefreshTokenThreshold
		*out = new(v1.Duration)
		**out = **in
	}
	if in.AllowedAudiences != nil {
		in, out := &in.AllowedAudiences, &out.AllowedAudiences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InsecureSkipVerify != nil {
		in, out := &in.InsecureSkipVerify, &out.InsecureSkipVerify
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCConfig.
func (in *OIDCConfig) DeepCopy() *OIDCConfig {
	if in == nil {
		return nil
	}
	out := new(OIDCConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCUserInfoConfig) DeepCopyInto(out *OIDCUserInfoConfig) {
	*out = *in
	if in.CacheExpiration != nil {
		in, out := &in.CacheExpiration, &out.CacheExpiration
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCUserInfoConfig.
func (in *OIDCUserInfoConfig) DeepCopy() *OIDCUserInfoConfig {
	if in == nil {
		return nil
	}
	out := new(OIDCUserInfoConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OTLPConfig) DeepCopyInto(out *OTLPConfig) {
	*out = *in
	if in.TLSEnabled != nil {
		in, out := &in.TLSEnabled, &out.TLSEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Attrs != nil {
		in, out := &in.Attrs, &out.Attrs
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OTLPConfig.
func (in *OTLPConfig) DeepCopy() *OTLPConfig {
	if in == nil {
		return nil
	}
	out := new(OTLPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OverrideIgnoreDiff) DeepCopyInto(out *OverrideIgnoreDiff) {
	*out = *in
	if in.JSONPointers != nil {
		in, out := &in.JSONPointers, &out.JSONPointers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.JQPathExpressions != nil {
		in, out := &in.JQPathExpressions, &out.JQPathExpressions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ManagedFieldsManagers != nil {
		in, out := &in.ManagedFieldsManagers, &out.ManagedFieldsManagers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OverrideIgnoreDiff.
func (in *OverrideIgnoreDiff) DeepCopy() *OverrideIgnoreDiff {
	if in == nil {
		return nil
	}
	out := new(OverrideIgnoreDiff)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProgressiveSyncsConfig) DeepCopyInto(out *ProgressiveSyncsConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProgressiveSyncsConfig.
func (in *ProgressiveSyncsConfig) DeepCopy() *ProgressiveSyncsConfig {
	if in == nil {
		return nil
	}
	out := new(ProgressiveSyncsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBACConfig) DeepCopyInto(out *RBACConfig) {
	*out = *in
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PolicyOverlays != nil {
		in, out := &in.PolicyOverlays, &out.PolicyOverlays
		*out = make([]RBACPolicyOverlay, len(*in))
		copy(*out, *in)
	}
	if in.ApplicationFineGrainedInheritanceEnabled != nil {
		in, out := &in.ApplicationFineGrainedInheritanceEnabled, &out.ApplicationFineGrainedInheritanceEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBACConfig.
func (in *RBACConfig) DeepCopy() *RBACConfig {
	if in == nil {
		return nil
	}
	out := new(RBACConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBACPolicyOverlay) DeepCopyInto(out *RBACPolicyOverlay) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBACPolicyOverlay.
func (in *RBACPolicyOverlay) DeepCopy() *RBACPolicyOverlay {
	if in == nil {
		return nil
	}
	out := new(RBACPolicyOverlay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReconciliationConfig) DeepCopyInto(out *ReconciliationConfig) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.HardTimeout != nil {
		in, out := &in.HardTimeout, &out.HardTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Jitter != nil {
		in, out := &in.Jitter, &out.Jitter
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReconciliationConfig.
func (in *ReconciliationConfig) DeepCopy() *ReconciliationConfig {
	if in == nil {
		return nil
	}
	out := new(ReconciliationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisConfig) DeepCopyInto(out *RedisConfig) {
	*out = *in
	if in.Sentinel != nil {
		in, out := &in.Sentinel, &out.Sentinel
		*out = new(RedisSentinelConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DB != nil {
		in, out := &in.DB, &out.DB
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisConfig.
func (in *RedisConfig) DeepCopy() *RedisConfig {
	if in == nil {
		return nil
	}
	out := new(RedisConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisSentinelConfig) DeepCopyInto(out *RedisSentinelConfig) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisSentinelConfig.
func (in *RedisSentinelConfig) DeepCopy() *RedisSentinelConfig {
	if in == nil {
		return nil
	}
	out := new(RedisSentinelConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoServerCacheConfig) DeepCopyInto(out *RepoServerCacheConfig) {
	*out = *in
	if in.DefaultExpiration != nil {
		in, out := &in.DefaultExpiration, &out.DefaultExpiration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.RepoExpiration != nil {
		in, out := &in.RepoExpiration, &out.RepoExpiration
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoServerCacheConfig.
func (in *RepoServerCacheConfig) DeepCopy() *RepoServerCacheConfig {
	if in == nil {
		return nil
	}
	out := new(RepoServerCacheConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoServerClientConfig) DeepCopyInto(out *RepoServerClientConfig) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.TLSEnabled != nil {
		in, out := &in.TLSEnabled, &out.TLSEnabled
		*out = new(bool)
		**out = **in
	}
	if in.InsecureSkipVerify != nil {
		in, out := &in.InsecureSkipVerify, &out.InsecureSkipVerify
		*out = new(bool)
		**out = **in
	}
	if in.MTLS != nil {
		in, out := &in.MTLS, &out.MTLS
		*out = new(MTLSCertConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoServerClientConfig.
func (in *RepoServerClientConfig) DeepCopy() *RepoServerClientConfig {
	if in == nil {
		return nil
	}
	out := new(RepoServerClientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoServerConfig) DeepCopyInto(out *RepoServerConfig) {
	*out = *in
	if in.Client != nil {
		in, out := &in.Client, &out.Client
		*out = new(RepoServerClientConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ParallelismLimit != nil {
		in, out := &in.ParallelismLimit, &out.ParallelismLimit
		*out = new(int32)
		**out = **in
	}
	if in.Listen != nil {
		in, out := &in.Listen, &out.Listen
		*out = new(ListenConfig)
		**out = **in
	}
	if in.TLSEnabled != nil {
		in, out := &in.TLSEnabled, &out.TLSEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Git != nil {
		in, out := &in.Git, &out.Git
		*out = new(RepoServerGitConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowOOBSymlinks != nil {
		in, out := &in.AllowOOBSymlinks, &out.AllowOOBSymlinks
		*out = new(bool)
		**out = **in
	}
	if in.IncludeHiddenDirectories != nil {
		in, out := &in.IncludeHiddenDirectories, &out.IncludeHiddenDirectories
		*out = new(bool)
		**out = **in
	}
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(RepoServerCacheConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxCombinedDirectoryManifestsSize != nil {
		in, out := &in.MaxCombinedDirectoryManifestsSize, &out.MaxCombinedDirectoryManifestsSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.StreamedManifest != nil {
		in, out := &in.StreamedManifest, &out.StreamedManifest
		*out = new(StreamedManifestConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Plugin != nil {
		in, out := &in.Plugin, &out.Plugin
		*out = new(RepoServerPluginConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ProfileEnabled != nil {
		in, out := &in.ProfileEnabled, &out.ProfileEnabled
		*out = new(bool)
		**out = **in
	}
	if in.GRPCTXTServiceConfigEnabled != nil {
		in, out := &in.GRPCTXTServiceConfigEnabled, &out.GRPCTXTServiceConfigEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSVersionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.OCI != nil {
		in, out := &in.OCI, &out.OCI
		*out = new(RepoServerOCIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.GRPCMaxSize != nil {
		in, out := &in.GRPCMaxSize, &out.GRPCMaxSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.RevisionCacheLockTimeout != nil {
		in, out := &in.RevisionCacheLockTimeout, &out.RevisionCacheLockTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Jsonnet != nil {
		in, out := &in.Jsonnet, &out.Jsonnet
		*out = new(JsonnetConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Log != nil {
		in, out := &in.Log, &out.Log
		*out = new(LogConfig)
		**out = **in
	}
	if in.Kustomize != nil {
		in, out := &in.Kustomize, &out.Kustomize
		*out = new(KustomizeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Helm != nil {
		in, out := &in.Helm, &out.Helm
		*out = new(HelmConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoServerConfig.
func (in *RepoServerConfig) DeepCopy() *RepoServerConfig {
	if in == nil {
		return nil
	}
	out := new(RepoServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoServerGitConfig) DeepCopyInto(out *RepoServerGitConfig) {
	*out = *in
	if in.SubmoduleEnabled != nil {
		in, out := &in.SubmoduleEnabled, &out.SubmoduleEnabled
		*out = new(bool)
		**out = **in
	}
	if in.RequestTimeout != nil {
		in, out := &in.RequestTimeout, &out.RequestTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.LSRemoteParallelismLimit != nil {
		in, out := &in.LSRemoteParallelismLimit, &out.LSRemoteParallelismLimit
		*out = new(int32)
		**out = **in
	}
	if in.BuiltinConfigEnabled != nil {
		in, out := &in.BuiltinConfigEnabled, &out.BuiltinConfigEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoServerGitConfig.
func (in *RepoServerGitConfig) DeepCopy() *RepoServerGitConfig {
	if in == nil {
		return nil
	}
	out := new(RepoServerGitConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoServerOCIConfig) DeepCopyInto(out *RepoServerOCIConfig) {
	*out = *in
	if in.Manifest != nil {
		in, out := &in.Manifest, &out.Manifest
		*out = new(OCIManifestConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.LayerMediaTypes != nil {
		in, out := &in.LayerMediaTypes, &out.LayerMediaTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoServerOCIConfig.
func (in *RepoServerOCIConfig) DeepCopy() *RepoServerOCIConfig {
	if in == nil {
		return nil
	}
	out := new(RepoServerOCIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoServerPluginConfig) DeepCopyInto(out *RepoServerPluginConfig) {
	*out = *in
	if in.UseManifestGeneratePaths != nil {
		in, out := &in.UseManifestGeneratePaths, &out.UseManifestGeneratePaths
		*out = new(bool)
		**out = **in
	}
	if in.TarExclusionGlobs != nil {
		in, out := &in.TarExclusionGlobs, &out.TarExclusionGlobs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoServerPluginConfig.
func (in *RepoServerPluginConfig) DeepCopy() *RepoServerPluginConfig {
	if in == nil {
		return nil
	}
	out := new(RepoServerPluginConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceActionDefinition) DeepCopyInto(out *ResourceActionDefinition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceActionDefinition.
func (in *ResourceActionDefinition) DeepCopy() *ResourceActionDefinition {
	if in == nil {
		return nil
	}
	out := new(ResourceActionDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceActionsConfig) DeepCopyInto(out *ResourceActionsConfig) {
	*out = *in
	if in.Definitions != nil {
		in, out := &in.Definitions, &out.Definitions
		*out = make([]ResourceActionDefinition, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceActionsConfig.
func (in *ResourceActionsConfig) DeepCopy() *ResourceActionsConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceActionsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceConfig) DeepCopyInto(out *ResourceConfig) {
	*out = *in
	if in.Exclusions != nil {
		in, out := &in.Exclusions, &out.Exclusions
		*out = make([]FilteredResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Inclusions != nil {
		in, out := &in.Inclusions, &out.Inclusions
		*out = make([]FilteredResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Customizations != nil {
		in, out := &in.Customizations, &out.Customizations
		*out = make([]ResourceCustomization, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SensitiveMaskAnnotationKeys != nil {
		in, out := &in.SensitiveMaskAnnotationKeys, &out.SensitiveMaskAnnotationKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CustomLabelKeys != nil {
		in, out := &in.CustomLabelKeys, &out.CustomLabelKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EventLabels != nil {
		in, out := &in.EventLabels, &out.EventLabels
		*out = new(EventLabelsConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceConfig.
func (in *ResourceConfig) DeepCopy() *ResourceConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceCustomization) DeepCopyInto(out *ResourceCustomization) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = new(ResourceActionsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.IgnoreDifferences != nil {
		in, out := &in.IgnoreDifferences, &out.IgnoreDifferences
		*out = new(OverrideIgnoreDiff)
		(*in).DeepCopyInto(*out)
	}
	if in.IgnoreResourceUpdates != nil {
		in, out := &in.IgnoreResourceUpdates, &out.IgnoreResourceUpdates
		*out = new(OverrideIgnoreDiff)
		(*in).DeepCopyInto(*out)
	}
	if in.KnownTypeFields != nil {
		in, out := &in.KnownTypeFields, &out.KnownTypeFields
		*out = make([]KnownTypeField, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceCustomization.
func (in *ResourceCustomization) DeepCopy() *ResourceCustomization {
	if in == nil {
		return nil
	}
	out := new(ResourceCustomization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelfHealConfig) DeepCopyInto(out *SelfHealConfig) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Cooldown != nil {
		in, out := &in.Cooldown, &out.Cooldown
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Backoff != nil {
		in, out := &in.Backoff, &out.Backoff
		*out = new(BackoffConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelfHealConfig.
func (in *SelfHealConfig) DeepCopy() *SelfHealConfig {
	if in == nil {
		return nil
	}
	out := new(SelfHealConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerCacheConfig) DeepCopyInto(out *ServerCacheConfig) {
	*out = *in
	if in.AppStateExpiration != nil {
		in, out := &in.AppStateExpiration, &out.AppStateExpiration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.ConnectionStatusExpiration != nil {
		in, out := &in.ConnectionStatusExpiration, &out.ConnectionStatusExpiration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.DefaultExpiration != nil {
		in, out := &in.DefaultExpiration, &out.DefaultExpiration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.OIDCExpiration != nil {
		in, out := &in.OIDCExpiration, &out.OIDCExpiration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.GlobCacheSize != nil {
		in, out := &in.GlobCacheSize, &out.GlobCacheSize
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerCacheConfig.
func (in *ServerCacheConfig) DeepCopy() *ServerCacheConfig {
	if in == nil {
		return nil
	}
	out := new(ServerCacheConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerConfig) DeepCopyInto(out *ServerConfig) {
	*out = *in
	if in.URLs != nil {
		in, out := &in.URLs, &out.URLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TLSEnabled != nil {
		in, out := &in.TLSEnabled, &out.TLSEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Log != nil {
		in, out := &in.Log, &out.Log
		*out = new(LogConfig)
		**out = **in
	}
	if in.Listen != nil {
		in, out := &in.Listen, &out.Listen
		*out = new(ServerListenConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthEnabled != nil {
		in, out := &in.AuthEnabled, &out.AuthEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ProxyExtensionEnabled != nil {
		in, out := &in.ProxyExtensionEnabled, &out.ProxyExtensionEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SyncReplaceAllowed != nil {
		in, out := &in.SyncReplaceAllowed, &out.SyncReplaceAllowed
		*out = new(bool)
		**out = **in
	}
	if in.APIContentTypes != nil {
		in, out := &in.APIContentTypes, &out.APIContentTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HTTPCookieMaxNumber != nil {
		in, out := &in.HTTPCookieMaxNumber, &out.HTTPCookieMaxNumber
		*out = new(int32)
		**out = **in
	}
	if in.ApplicationTreeShardSize != nil {
		in, out := &in.ApplicationTreeShardSize, &out.ApplicationTreeShardSize
		*out = new(int32)
		**out = **in
	}
	if in.ProfileEnabled != nil {
		in, out := &in.ProfileEnabled, &out.ProfileEnabled
		*out = new(bool)
		**out = **in
	}
	if in.GRPCTXTServiceConfigEnabled != nil {
		in, out := &in.GRPCTXTServiceConfigEnabled, &out.GRPCTXTServiceConfigEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DexConnection != nil {
		in, out := &in.DexConnection, &out.DexConnection
		*out = new(DexConnectionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Cache != nil {
		in, out := &in.Cache, &out.Cache
		*out = new(ServerCacheConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSVersionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.K8sClient != nil {
		in, out := &in.K8sClient, &out.K8sClient
		*out = new(K8sClientConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = new(ServerLogsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Dex != nil {
		in, out := &in.Dex, &out.Dex
		*out = new(DexConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(OIDCConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RBAC != nil {
		in, out := &in.RBAC, &out.RBAC
		*out = new(RBACConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.UI != nil {
		in, out := &in.UI, &out.UI
		*out = new(UIConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Accounts != nil {
		in, out := &in.Accounts, &out.Accounts
		*out = make([]AccountConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Extensions != nil {
		in, out := &in.Extensions, &out.Extensions
		*out = make([]ExtensionConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeepLinks != nil {
		in, out := &in.DeepLinks, &out.DeepLinks
		*out = new(DeepLinksConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Help != nil {
		in, out := &in.Help, &out.Help
		*out = new(HelpConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = new(UsersConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.GoogleAnalytics != nil {
		in, out := &in.GoogleAnalytics, &out.GoogleAnalytics
		*out = new(GoogleAnalyticsConfig)
		**out = **in
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(WebhookConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Exec != nil {
		in, out := &in.Exec, &out.Exec
		*out = new(ExecConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.StatusBadge != nil {
		in, out := &in.StatusBadge, &out.StatusBadge
		*out = new(StatusBadgeConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerConfig.
func (in *ServerConfig) DeepCopy() *ServerConfig {
	if in == nil {
		return nil
	}
	out := new(ServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerListenConfig) DeepCopyInto(out *ServerListenConfig) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.MetricsPort != nil {
		in, out := &in.MetricsPort, &out.MetricsPort
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerListenConfig.
func (in *ServerListenConfig) DeepCopy() *ServerListenConfig {
	if in == nil {
		return nil
	}
	out := new(ServerListenConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerLogsConfig) DeepCopyInto(out *ServerLogsConfig) {
	*out = *in
	if in.MaxPodsToRender != nil {
		in, out := &in.MaxPodsToRender, &out.MaxPodsToRender
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerLogsConfig.
func (in *ServerLogsConfig) DeepCopy() *ServerLogsConfig {
	if in == nil {
		return nil
	}
	out := new(ServerLogsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceHydratorConfig) DeepCopyInto(out *SourceHydratorConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceHydratorConfig.
func (in *SourceHydratorConfig) DeepCopy() *SourceHydratorConfig {
	if in == nil {
		return nil
	}
	out := new(SourceHydratorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusBadgeConfig) DeepCopyInto(out *StatusBadgeConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusBadgeConfig.
func (in *StatusBadgeConfig) DeepCopy() *StatusBadgeConfig {
	if in == nil {
		return nil
	}
	out := new(StatusBadgeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamedManifestConfig) DeepCopyInto(out *StreamedManifestConfig) {
	*out = *in
	if in.MaxTarSize != nil {
		in, out := &in.MaxTarSize, &out.MaxTarSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxExtractedSize != nil {
		in, out := &in.MaxExtractedSize, &out.MaxExtractedSize
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamedManifestConfig.
func (in *StreamedManifestConfig) DeepCopy() *StreamedManifestConfig {
	if in == nil {
		return nil
	}
	out := new(StreamedManifestConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncImpersonationConfig) DeepCopyInto(out *SyncImpersonationConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncImpersonationConfig.
func (in *SyncImpersonationConfig) DeepCopy() *SyncImpersonationConfig {
	if in == nil {
		return nil
	}
	out := new(SyncImpersonationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncWaveConfig) DeepCopyInto(out *SyncWaveConfig) {
	*out = *in
	if in.Delay != nil {
		in, out := &in.Delay, &out.Delay
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncWaveConfig.
func (in *SyncWaveConfig) DeepCopy() *SyncWaveConfig {
	if in == nil {
		return nil
	}
	out := new(SyncWaveConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSVersionConfig) DeepCopyInto(out *TLSVersionConfig) {
	*out = *in
	if in.Ciphers != nil {
		in, out := &in.Ciphers, &out.Ciphers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSVersionConfig.
func (in *TLSVersionConfig) DeepCopy() *TLSVersionConfig {
	if in == nil {
		return nil
	}
	out := new(TLSVersionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIBannerConfig) DeepCopyInto(out *UIBannerConfig) {
	*out = *in
	if in.Permanent != nil {
		in, out := &in.Permanent, &out.Permanent
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIBannerConfig.
func (in *UIBannerConfig) DeepCopy() *UIBannerConfig {
	if in == nil {
		return nil
	}
	out := new(UIBannerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UIConfig) DeepCopyInto(out *UIConfig) {
	*out = *in
	if in.Banner != nil {
		in, out := &in.Banner, &out.Banner
		*out = new(UIBannerConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UIConfig.
func (in *UIConfig) DeepCopy() *UIConfig {
	if in == nil {
		return nil
	}
	out := new(UIConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsersConfig) DeepCopyInto(out *UsersConfig) {
	*out = *in
	if in.AnonymousEnabled != nil {
		in, out := &in.AnonymousEnabled, &out.AnonymousEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SessionDuration != nil {
		in, out := &in.SessionDuration, &out.SessionDuration
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsersConfig.
func (in *UsersConfig) DeepCopy() *UsersConfig {
	if in == nil {
		return nil
	}
	out := new(UsersConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookConfig) DeepCopyInto(out *WebhookConfig) {
	*out = *in
	if in.MaxPayloadSize != nil {
		in, out := &in.MaxPayloadSize, &out.MaxPayloadSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Refresh != nil {
		in, out := &in.Refresh, &out.Refresh
		*out = new(WebhookRefreshConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ParallelismLimit != nil {
		in, out := &in.ParallelismLimit, &out.ParallelismLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookConfig.
func (in *WebhookConfig) DeepCopy() *WebhookConfig {
	if in == nil {
		return nil
	}
	out := new(WebhookConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookRefreshConfig) DeepCopyInto(out *WebhookRefreshConfig) {
	*out = *in
	if in.Jitter != nil {
		in, out := &in.Jitter, &out.Jitter
		*out = new(v1.Duration)
		**out = **in
	}
	if in.JitterThreshold != nil {
		in, out := &in.JitterThreshold, &out.JitterThreshold
		*out = new(int32)
		**out = **in
	}
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookRefreshConfig.
func (in *WebhookRefreshConfig) DeepCopy() *WebhookRefreshConfig {
	if in == nil {
		return nil
	}
	out := new(WebhookRefreshConfig)
	in.DeepCopyInto(out)
	return out
}
